version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/app/logs
      - .:/app:ro
    ports:
      - 8000:8000
    restart: always
    tty: true
    env_file: 
    - .env
