version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/app/logs
      - .:/app:ro
    ports:
      - 80:80
    tty: true
    env_file: .env
